### ISSUE TITLE
Update PyPI entry

### ISSUE THREAD

**Issue by htgoebel** [KeyWeeUsr/python-dis3#2]
The [PyPi entry](https://pypi.org/project/dis3/) states the homepage is https://github.com/tomxtobin/dis3, which is no longer existing. This leaves the impression the project is abandoned.

Please manually update the PyPI entry to point to https://github.com/KeyWeeUsr/python-dis3/. Thanks

**Comment by KeyWeeUsr** [comment]
Thanks. Closed by https://github.com/KeyWeeUsr/python-dis3/commit/39ec07ff7a054fe2c2514916671f692b6e4d01fc.

**Comment by htgoebel** [comment]
Thanks for the quick response and the new release :-)
